//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLocation
    {
        public int TicketLocId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<int> HouseNo { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string ParcelNo { get; set; }
        public string CrossSt1 { get; set; }
        public string CrossSt2 { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
