//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketLocAdditionals = new HashSet<TicketLocAdditional>();
            this.TicketLocations = new HashSet<TicketLocation>();
            this.TicAttachments = new HashSet<TicAttachment>();
            this.TicReplies = new HashSet<TicReply>();
        }
    
        public int TicketId { get; set; }
        public string Subject { get; set; }
        public string ConstituentID { get; set; }
        public int Service { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<int> IssueDetailId { get; set; }
        public Nullable<int> IssueAddInfoId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateReported { get; set; }
        public Nullable<System.TimeSpan> TimeReported { get; set; }
        public int TicketStatus { get; set; }
    
        public virtual IssueAddInfo IssueAddInfo { get; set; }
        public virtual IssueDetail IssueDetail { get; set; }
        public virtual Issue Issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketLocAdditional> TicketLocAdditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketLocation> TicketLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicAttachment> TicAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicReply> TicReplies { get; set; }
    }
}
