//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLocAdditional
    {
        public int TicketLocAddId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public int JurisdictionCode { get; set; }
        public int MinorCivilDiv { get; set; }
        public int StateAssembly { get; set; }
        public int StateSenate { get; set; }
        public int CityWard { get; set; }
        public int CommissionDist { get; set; }
        public int Commissioner { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
